### ISSUE TITLE
Consider the proof for the robustness of hopping-through-corridor strategy & implement method to get 'strip indices' for any given corridor (given r)

### ISSUE THREAD

**Issue by binchoi** [binchoi/TimingMaze#10]
# Description

## Task

There are two tasks

- [ ] Consider the hopping-through-corridor strategy as default logic for player as it moves through a corridor (as opposed to walking through corridor, which hits all x values (strips) from start to end-target (1, 2, 3, 4, 5,). (note. In vertical corridor, y values would be _strip indices_ )
    - [ ] The result of this consideration might be, given cells are 1x1 and radius is an integer, we know that corridors will be skippable if r is greater/less than a and non skippable when .... 
    - [ ] Writing up the proof might be useful for the report (but I think we can do that later when we have more report writing time!)
- [ ] If hopping-through-corridor is a valid, robust way to move faster through a corridor while being able to robustly cover all cells in that corridor, implement a method that: given corridor (x-range, y-range) and radius r, outputs the strip indices as a list = (e.g., it may be [1, 2,3, 4, 5,6 , 7, 8, 9] , or [1, 3, 5, 7, ...] in a skippable corridor/setting)
    - [ ] I will be calling this method when creating the corridors. I will provide it, the x, y ranges and radius r. -> this strip-list will be a field in corridor.

<img width="1188" alt="Screenshot 2024-09-21 at 10 05 47 PM" src="https://github.com/user-attachments/assets/5782da6a-dd59-4dad-822d-cb80f3d3a400">
